version: 2

enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "flutter"
      - dependency-name: "sdk"
    labels:
      - "dependencies"
      - "pub"

  - package-ecosystem: "gradle"
    directory: "/android/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directories:
      - "/.github/workflows"
      - "/.github/actions/android"
      - "/.github/actions/common"
      - "/.github/actions/ios"
      - "/.github/actions/screenshot-android"
    schedule:
      interval: "daily"
