name: "iOS Workflow"

inputs:
  VERSION_NAME:
    description: 'Version Name to be used for build'
    required: false
    default: '1.0.0'
  VERSION_CODE:
    description: 'Version Code to be used for build'
    required: true
    default: '1'

runs:
  using: "composite"
  steps:
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        cache: false # TODO set to <true> after https://github.com/actions/runner/issues/449 is fixed
        flutter-version-file: pubspec.yaml

    - name: Update Podfile
      shell: bash
      run: |
        cd ./iOS
        flutter pub get
        pod install --repo-update

    - name: Build iOS IPA (No code signing for PRs)
      # if: ${{ github.event_name == 'pull_request' }} # TODO: Uncomment once iOS certs are renewed.
      shell: bash
      env:
        VERSION_NAME: ${{ inputs.VERSION_NAME }}
        VERSION_CODE: ${{ inputs.VERSION_CODE }}
      run: |
        flutter build ios --release --no-codesign --build-name "$VERSION_NAME" --build-number "$VERSION_CODE"

        cd build/ios/iphoneos
        mkdir Payload
        cp -r Runner.app Payload/
        zip -qr pslab-unsigned.ipa Payload/
        mv pslab-unsigned.ipa ../../../

    # - name: Build Signed iOS IPA (For Production) # TODO: Uncomment once iOS certs are renewed.
    #  if: ${{ github.event_name != 'pull_request' }}
    #  shell: bash
    #  env:
    #    VERSION_NAME: ${{ inputs.VERSION_NAME }}
    #   VERSION_CODE: ${{ inputs.VERSION_CODE }}
    # run: |
        # flutter build ipa --build-name "$VERSION_NAME" --build-number "$VERSION_CODE"

    - name: Store IPA file
      uses: actions/upload-artifact@v7
      with:
        name: iOS IPA Generated
        path: |
          pslab-unsigned.ipa
          build/ios/ipa/*.ipa
        if-no-files-found: ignore