name: "Common Workflow"

runs:
  using: "composite"
  steps:
    - name: Set up Flutter
      if: runner.os != 'macOS' # TODO remove after https://github.com/actions/runner/issues/449 is fixed
      uses: subosito/flutter-action@v2
      with:
        cache: true
        flutter-version-file: .flutter-version

    - name: Fetch Flutter Dependencies
      shell: bash
      run: |
        flutter pub get
        dart format lib/l10n/

    - name: Validate Code Format
      shell: bash
      run: dart format --output=none --set-exit-if-changed .

    - name: Analyze Code
      shell: bash
      run: flutter analyze

    - name: Run tests
      shell: bash
      run: flutter test