// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `IS_USING_WS`, `SERIAL_PORT`, `WIFI_TCP_STREAM`, `WIFI_WS_STREAM`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `deref`, `deref`, `deref`, `initialize`, `initialize`, `initialize`, `initialize`

Future<void> initDesktop({required int vid, required int pid}) =>
    RustLib.instance.api.crateApiSimpleInitDesktop(vid: vid, pid: pid);

Future<void> initAndroid({required int fd}) =>
    RustLib.instance.api.crateApiSimpleInitAndroid(fd: fd);

void setBaudRate({required int baudRate}) =>
    RustLib.instance.api.crateApiSimpleSetBaudRate(baudRate: baudRate);

void setDtr({required bool state}) =>
    RustLib.instance.api.crateApiSimpleSetDtr(state: state);

void setRts({required bool state}) =>
    RustLib.instance.api.crateApiSimpleSetRts(state: state);

void writeData({required List<int> data}) =>
    RustLib.instance.api.crateApiSimpleWriteData(data: data);

Future<Uint8List> readData(
        {required int bytesToRead, required int timeoutMs}) =>
    RustLib.instance.api
        .crateApiSimpleReadData(bytesToRead: bytesToRead, timeoutMs: timeoutMs);

void closeUsb() => RustLib.instance.api.crateApiSimpleCloseUsb();

bool checkDesktopDevicePresent() =>
    RustLib.instance.api.crateApiSimpleCheckDesktopDevicePresent();

void wifiConnect(
        {required String host,
        required int port,
        required bool useWebsocket}) =>
    RustLib.instance.api.crateApiSimpleWifiConnect(
        host: host, port: port, useWebsocket: useWebsocket);

Future<Uint8List> wifiRead(
        {required int bytesToRead, required int timeoutMs}) =>
    RustLib.instance.api
        .crateApiSimpleWifiRead(bytesToRead: bytesToRead, timeoutMs: timeoutMs);

void wifiWrite({required List<int> data}) =>
    RustLib.instance.api.crateApiSimpleWifiWrite(data: data);

void wifiDisconnect() => RustLib.instance.api.crateApiSimpleWifiDisconnect();

void pushWebData({required List<int> data}) =>
    RustLib.instance.api.crateApiSimplePushWebData(data: data);

Uint8List readWebData({required int bytesToRead}) =>
    RustLib.instance.api.crateApiSimpleReadWebData(bytesToRead: bytesToRead);
