name: "Linux ARM64 Workflow"

inputs:
  VERSION_NAME:
    description: "Version Name to be used for build"
    required: false
    default: "1.0.0"

  VERSION_CODE:
    description: "Version Code to be used for build"
    required: true
    default: "1"

runs:
  using: "composite"
  steps:
    - name: Install dependencies from Apt
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          curl git unzip xz-utils zip libglu1-mesa clang cmake ninja-build \
          pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev

    - name: Read Flutter version
      shell: bash
      run: |
        FLUTTER_VERSION=$(cat .flutter-version)
        echo "Using Flutter version: $FLUTTER_VERSION"
        echo "FLUTTER_VERSION=$FLUTTER_VERSION" >> $GITHUB_ENV

    - name: Clone Flutter
      shell: bash
      run: |
        git clone --depth 1 --branch "$FLUTTER_VERSION" https://github.com/flutter/flutter.git "$RUNNER_TEMP/flutter"
        echo "$RUNNER_TEMP/flutter/bin" >> "$GITHUB_PATH"

    - name: Install Flutter
      shell: bash
      run: flutter doctor

    - name: Build Linux App
      shell: bash
      run: |
        flutter config --enable-linux-desktop
        source linux/prep.sh
        flutter build linux \
          --build-name "${{ inputs.VERSION_NAME }}" \
          --build-number "${{ inputs.VERSION_CODE }}"

    - name: Install fpm
      shell: bash
      run: |
        sudo apt-get install -y ruby ruby-dev build-essential
        sudo gem install --no-document fpm

    - name: Build .deb package
      shell: bash
      run: |
        fpm -s dir -t deb \
          -n pslab \
          -v "${{ inputs.VERSION_NAME }}" \
          --prefix=/ \
          --depends libusb-1.0-0 \
          build/linux/arm64/release/bundle/bin/=/usr/bin \
          build/linux/arm64/release/bundle/lib/pslab/=/usr/lib/pslab \
          build/linux/arm64/release/bundle/share/pslab/=/usr/share/pslab \
          linux/pslab.desktop=/usr/share/applications/pslab.desktop \
          linux/assets/pslab.png=/usr/share/icons/hicolor/512x512/apps/pslab.png \
          linux/99-pslab.rules=/etc/udev/rules.d/99-pslab.rules

    - name: Build .rpm package
      shell: bash
      run: |
        fpm -s dir -t rpm \
          -n pslab \
          -v "${{ inputs.VERSION_NAME }}" \
          --prefix=/ \
          --depends libusb1 \
          build/linux/arm64/release/bundle/bin/=/usr/bin \
          build/linux/arm64/release/bundle/lib/pslab/=/usr/lib/pslab \
          build/linux/arm64/release/bundle/share/pslab/=/usr/share/pslab \
          linux/pslab.desktop=/usr/share/applications/pslab.desktop \
          linux/assets/pslab.png=/usr/share/icons/hicolor/512x512/apps/pslab.png \
          linux/99-pslab.rules=/etc/udev/rules.d/99-pslab.rules

    - name: Store Packages
      uses: actions/upload-artifact@v4
      with:
        name: linux-packages-arm64
        path: |
          *.deb
          *.rpm