name: Build

on:
  pull_request:
    branches: ["flutter"]
    paths:
      - '**.md'
      - 'docs/**'
      - '**.png'
      - '**.jpg'
      - '**.jpeg'
      - '**.gif'
      - '**.svg'
      - '**.webp'
      - '**.txt'
      - '**.arb'

jobs:
  android:
    name: Android Flutter Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "non-code changes."

  ios:
    name: iOS Flutter Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "non-code changes."
